title: "Mon blog"
email: "contact@dblink.fr"
description: "Blog DBLINK"
baseurl: "/dblinkweb" # Si votre blog est à la racine du domaine, laissez cette valeur vide.
url: "https://mondomaine.com" # L'URL principale de votre site
twitter_username: sdblink
github_username: sdblink

# Paramètres de build
markdown: kramdown
theme: minima

# Paramètres de pagination
paginate: 5
paginate_path: "/page:num/"

# Paramètres d'exclusion
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  blog:
    output: true
    permalink: /blog/:name.html
